name: Lint and Test

on:
  pull_request

permissions:
  contents: read

env:
  IMAGE_NAME: canton-backup-utility

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Docker Build
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: lint
        run: docker run --entrypoint /usr/local/bin/poetry ${{ env.IMAGE_NAME }} run pylint src

      - name: Run App tests
        run: docker run --entrypoint /usr/local/bin/poetry ${{ env.IMAGE_NAME }} run pytest tests
